doublecmd 0.9.1-7: 	* product update --> 0.9.1 	* switched downloader from wget to curl 	* matching changelog for release in control file

diff --git a/SRC/CLIENT_DATA/product_downloader.sh.in b/SRC/CLIENT_DATA/product_downloader.sh.in
--- a/SRC/CLIENT_DATA/product_downloader.sh.in
+++ b/SRC/CLIENT_DATA/product_downloader.sh.in
@@ -4,7 +4,7 @@
 # Product: Double Commander
 #
 # Version 1.3
-# Jens Boettge <boettge@mpi-halle.mpg.de>  2018-09-18 08:35:02 +0200
+# Jens Boettge <boettge@mpi-halle.mpg.de>  2019-02-27 08:45:46 +0100
 #=======================================================================
 # link examples:
 # https://sourceforge.net/p/doublecmd/wiki/Download/
@@ -16,12 +16,26 @@
 
 ERR=0
 THIS_DIR=$(dirname $(readlink -f $0))
+DOWNLOADER="curl"
 
-WGET=$(which wget)
-if [ -z "$WGET" ];   then echo "Error: wget not found" ;  exit 200 ; fi
 MD5EXE=$(which md5sum)
-if [ -z "$MD5EXE" ]; then echo "Error: md5sum not found"; exit 201 ; fi
+if [ -z "$MD5EXE" ]; then echo "Error: md5sum not found"; exit 200 ; fi
 
+if [ "$DOWNLOADER" = "wget" ]; then
+	WGET=$(which wget)
+	if [ -z "$WGET" ];   then echo "Error: wget not found" ;  exit 201 ; fi
+	#options for wget:
+	DL_OPTS="--max-redirect=6 --no-cookies -nv "
+	DL_OUT="-O"
+fi
+
+if [ "$DOWNLOADER" = "curl" ]; then
+	CURL=$(which curl)
+	if [ -z "$CURL" ];   then echo "Error: curl not found" ;  exit 202 ; fi
+	#options for curl:
+	DL_OPTS="--silent --show-error -L "
+	DL_OUT="-o"
+fi
 
 if [ -f "${THIS_DIR}/Makefile" ] ; then
 	# Skript is running in the context of building OPSI package via make
@@ -48,7 +62,7 @@ fi
 #	exit $ERR
 #fi
 
-BASE="http://sourceforge.net/projects/doublecmd/files/DC\ for\ Windows\ %%ARCH%%\ bit/Double\ Commander\ ${VERSION}\ beta/doublecmd-${VERSION}.%%WARCH%%.exe/download"
+BASE="https://sourceforge.net/projects/doublecmd/files/DC\ for\ Windows\ %%ARCH%%\ bit/Double\ Commander\ ${VERSION}\ beta/doublecmd-${VERSION}.%%WARCH%%.exe/download"
 PKG_FILE="${PROD}-${VERSION}-x%%ARCH%%.exe"
 
 # in postinst: DEST_DIR=DST="${CLIENT_DATA_DIR}/files"
@@ -63,7 +77,6 @@ DEST_DIR=${DEST_DIR%\/}
 
 MD5SUMS="${PROD}.md5sums"
 CNT=0
-WGET_OPTS="--max-redirect=5 --no-cookies "
 FS_THRESHOLD=10000
 
 calc_md5()
@@ -110,7 +123,7 @@ download()
         if [ -f "${DEST_DIR}/${PACKAGE}" ]; then
                 echo -e "\tFile already exists"
         else
-                eval wget ${WGET_OPTS} -nv "${DL_URL}" -O "${DEST_DIR}/${PACKAGE}"
+                eval ${DOWNLOADER} ${DL_OPTS} "${DL_URL}" ${DL_OUT} "${DEST_DIR}/${PACKAGE}"
                 if  [ ! -f "${DEST_DIR}/${PACKAGE}" ]; then
                         let "ERR+=1"
                 else
